// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	sendToClaude: (messages: ChatMessage[], chatId: string, system: string, model: string, options: RequestOptions) => __TAURI_INVOKE<void>("send_to_claude", { messages, chatId, system, model, options }),
	cancelStream: (chatId: string) => __TAURI_INVOKE<void>("cancel_stream", { chatId }),
	countChatTokens: (messages: ChatMessage[], system: string, model: string, options: RequestOptions) => __TAURI_INVOKE<number>("count_chat_tokens", { messages, system, model, options }),
	probeConnectivity: () => __TAURI_INVOKE<boolean>("probe_connectivity"),
	listModels: () => __TAURI_INVOKE<ModelInfo[]>("list_models"),
	loadChats: () => __TAURI_INVOKE<string>("load_chats"),
	saveChats: (json: string) => __TAURI_INVOKE<null>("save_chats", { json }),
	loadContextLibrary: () => __TAURI_INVOKE<string>("load_context_library"),
	saveContextLibrary: (json: string) => __TAURI_INVOKE<null>("save_context_library", { json }),
	readContextImportFile: (path: string) => __TAURI_INVOKE<string>("read_context_import_file", { path }),
	readContextPdfBytes: (dataBase64: string) => __TAURI_INVOKE<string>("read_context_pdf_bytes", { dataBase64 }),
	retryTranscription: () => __TAURI_INVOKE<void>("retry_transcription"),
	listAudioOutputDevices: () => __TAURI_INVOKE<OutputDeviceInfo[]>("list_audio_output_devices"),
	captureAvailable: () => __TAURI_INVOKE<boolean>("capture_available"),
	requestAudioCapturePermission: () => __TAURI_INVOKE<boolean>("request_audio_capture_permission"),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (newSettings: Settings) => __TAURI_INVOKE<Settings>("set_settings", { newSettings }),
	getOfficialPresets: () => __TAURI_INVOKE<PromptPreset[]>("get_official_presets"),
	setPttSuspended: (suspended: boolean) => __TAURI_INVOKE<void>("set_ptt_suspended", { suspended }),
	redeemAccessCode: (code: string, idempotencyKey: string) => __TAURI_INVOKE<null>("redeem_access_code", { code, idempotencyKey }),
	setWindowSize: (width: number | null, height: number | null) => __TAURI_INVOKE<void>("set_window_size", { width, height }),
	closeApp: () => __TAURI_INVOKE<void>("close_app"),
	hideMainWindow: () => __TAURI_INVOKE<void>("hide_main_window"),
	launchMainWindow: () => __TAURI_INVOKE<null>("launch_main_window"),
	stopMainWindow: () => __TAURI_INVOKE<null>("stop_main_window"),
	openAudioPermissionSettings: () => __TAURI_INVOKE<void>("open_audio_permission_settings"),
	openExternal: (url: string) => __TAURI_INVOKE<void>("open_external", { url }),
	setPreviewHtml: (html: string) => __TAURI_INVOKE<void>("set_preview_html", { html }),
	checkForUpdate: () => __TAURI_INVOKE<{
	version: string,
	notes: string,
	date: string | null,
} | null>("check_for_update"),
	installUpdate: () => __TAURI_INVOKE<null>("install_update"),
	getAppVersion: () => __TAURI_INVOKE<string>("get_app_version"),
	listIdentities: () => __TAURI_INVOKE<IdentityInfo[]>("list_identities"),
	setAppIdentity: (identityId: string) => __TAURI_INVOKE<null>("set_app_identity", { identityId }),
};

/* Constants */
export const MODIFIER_COMBOS = ["Cmd","Ctrl","Alt","Cmd+Shift","Ctrl+Shift","Alt+Shift"] as const;

export const SETTINGS_DEFAULTS = {"access_token":"","anthropic_api_key":"","auto_preview_html":true,"auto_send":false,"buffer_enabled":true,"buffer_seconds":4,"capture_device_uid":"","chat_font_size":13.5,"groq_api_key":"","hotkey":"F9","identity_id":"","move_modifier":"Cmd","move_step":20,"plugin_settings":[],"prompt_presets":[],"resize_modifier":"Cmd+Shift","resize_step":20,"screen_share_visible":false,"scroll_modifier":"Alt","scroll_step":120,"skipped_version":"","stt_language":"ru","stt_translate":false,"teleprompter_font_size":28.0,"teleprompter_hotkey":"F10","teleprompter_resume":true,"teleprompter_speed":40.0,"theme":"gray","toggle_hotkey":"Cmd+Shift+H","window_height":680.0,"window_opacity":0.9,"window_width":960.0} as const;

export const SETTINGS_LIMITS = {"bufferSeconds":{"default":4,"max":10,"min":4},"chatFontSize":{"default":13.5,"max":20.0,"min":10.0},"moveStep":{"default":20,"max":200,"min":1},"resizeStep":{"default":20,"max":200,"min":1},"scrollStep":{"default":120,"max":1000,"min":10},"teleprompterFontSize":{"default":28.0,"max":48.0,"min":20.0},"teleprompterSpeed":{"default":40.0,"max":150.0,"min":10.0},"windowHeight":{"default":680.0,"max":1100.0,"min":520.0},"windowOpacity":{"default":0.9,"max":1.0,"min":0.2},"windowWidth":{"default":960.0,"max":1600.0,"min":300.0}} as const;

/* Types */
export type AppError = {
	code: ErrorCode,
	message: string,
};

export type ChatMessage = {
	role: string,
	text: string,
	images?: ImageAttachment[],
};

export type ErrorCode = "network" | "badApiKey" | "badAccessCode" | "retryable" | "api" | "cancelled" | "permission" | "silence" | "internal";

export type IdentityInfo = {
	id: string,
	displayName: string,
	iconPngBase64: string,
};

export type ImageAttachment = {
	media_type: string,
	data: string,
};

export type LlmDelta = {
	chatId: string,
	delta: string,
};

export type LlmDone = {
	chatId: string,
};

export type LlmErrorEvent = {
	chatId: string,
	code: ErrorCode,
	message: string,
};

export type LlmUsage = {
	chatId: string,
	inputTokens: number,
};

export type ModelInfo = {
	id: string,
	displayName: string,
	adaptive: boolean,
	alwaysThinks: boolean,
	codeExec: boolean,
	maxInputTokens: number,
};

export type OutputDeviceInfo = {
	uid: string,
	name: string,
};

export type PluginSetting = {
	id: string,
	enabled: boolean,
	hotkey: string,
};

export type PromptPreset = {
	id: string,
	name: string,
	text: string,
};

export type RecorderState = "idle" | "recording" | "transcribing";

export type RequestOptions = {
	thinking?: boolean,
	webSearch?: boolean,
};

export type ResizeDim = "width" | "height";

export type ResizeKeyPayload = {
	dim: ResizeDim,
	dir: number,
};

export type Settings = {
	anthropic_api_key?: string,
	groq_api_key?: string,
	access_token?: string,
	prompt_presets?: PromptPreset[],
	hotkey?: string,
	auto_send?: boolean,
	window_opacity?: number | null,
	move_step?: number,
	auto_preview_html?: boolean,
	toggle_hotkey?: string,
	chat_font_size?: number | null,
	skipped_version?: string,
	stt_language?: string,
	stt_translate?: boolean,
	screen_share_visible?: boolean,
	teleprompter_speed?: number | null,
	teleprompter_font_size?: number | null,
	teleprompter_hotkey?: string,
	teleprompter_resume?: boolean,
	window_width?: number | null,
	window_height?: number | null,
	resize_step?: number,
	capture_device_uid?: string,
	theme?: string,
	scroll_step?: number,
	buffer_enabled?: boolean,
	buffer_seconds?: number,
	identity_id?: string,
	move_modifier?: string,
	resize_modifier?: string,
	scroll_modifier?: string,
	plugin_settings?: PluginSetting[],
};

export type UpdateDone = {
	version: string,
};

export type UpdateInfo = {
	version: string,
	notes: string,
	date: string | null,
};

export type UpdateProgress = {
	downloaded: number | null,
	total: number | null,
};

